spring:
  datasource:
    url: jdbc:mysql://localhost:23306/roomescape?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dev
    password: dev
  profiles:
    active: local
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none

jwt:
  secret: "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E="
  expiration: 1800000
  expirationInSeconds: 1800
